package bean;
// Generated 05/12/2023 10:44:54 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClientesEma generated by hbm2java
 */
@Entity
@Table(name="clientes_ema"
    ,catalog="db_eduardo_aguero"
)
public class ClientesEma  implements java.io.Serializable {


     private int idClienteEma;
     private String nomeCompletoEma;
     private Date dataNascimentoEma;
     private String generoEma;
     private String enderecoEma;
     private String cidadeEma;
     private String cepEma;
     private String telefoneEma;
     private String emailEma;
     private Date dataCadastroEma;
     private String paisEma;
     private String estadoEma;
     private String estadoCivilEma;
     private String cpfEma;
     private String rgEma;
     private String profissaoEma;

    public ClientesEma() {
    }

	
    public ClientesEma(int idClienteEma) {
        this.idClienteEma = idClienteEma;
    }
    public ClientesEma(int idClienteEma, String nomeCompletoEma, Date dataNascimentoEma, String generoEma, String enderecoEma, String cidadeEma, String cepEma, String telefoneEma, String emailEma, Date dataCadastroEma, String paisEma, String estadoEma, String estadoCivilEma, String cpfEma, String rgEma, String profissaoEma) {
       this.idClienteEma = idClienteEma;
       this.nomeCompletoEma = nomeCompletoEma;
       this.dataNascimentoEma = dataNascimentoEma;
       this.generoEma = generoEma;
       this.enderecoEma = enderecoEma;
       this.cidadeEma = cidadeEma;
       this.cepEma = cepEma;
       this.telefoneEma = telefoneEma;
       this.emailEma = emailEma;
       this.dataCadastroEma = dataCadastroEma;
       this.paisEma = paisEma;
       this.estadoEma = estadoEma;
       this.estadoCivilEma = estadoCivilEma;
       this.cpfEma = cpfEma;
       this.rgEma = rgEma;
       this.profissaoEma = profissaoEma;
    }
   
     @Id 

    
    @Column(name="id_cliente_ema", unique=true, nullable=false)
    public int getIdClienteEma() {
        return this.idClienteEma;
    }
    
    public void setIdClienteEma(int idClienteEma) {
        this.idClienteEma = idClienteEma;
    }

    
    @Column(name="nome_completo_ema", length=100)
    public String getNomeCompletoEma() {
        return this.nomeCompletoEma;
    }
    
    public void setNomeCompletoEma(String nomeCompletoEma) {
        this.nomeCompletoEma = nomeCompletoEma;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_nascimento_ema", length=10)
    public Date getDataNascimentoEma() {
        return this.dataNascimentoEma;
    }
    
    public void setDataNascimentoEma(Date dataNascimentoEma) {
        this.dataNascimentoEma = dataNascimentoEma;
    }

    
    @Column(name="genero_ema", length=20)
    public String getGeneroEma() {
        return this.generoEma;
    }
    
    public void setGeneroEma(String generoEma) {
        this.generoEma = generoEma;
    }

    
    @Column(name="endereco_ema")
    public String getEnderecoEma() {
        return this.enderecoEma;
    }
    
    public void setEnderecoEma(String enderecoEma) {
        this.enderecoEma = enderecoEma;
    }

    
    @Column(name="cidade_ema", length=100)
    public String getCidadeEma() {
        return this.cidadeEma;
    }
    
    public void setCidadeEma(String cidadeEma) {
        this.cidadeEma = cidadeEma;
    }

    
    @Column(name="cep_ema", length=10)
    public String getCepEma() {
        return this.cepEma;
    }
    
    public void setCepEma(String cepEma) {
        this.cepEma = cepEma;
    }

    
    @Column(name="telefone_ema", length=20)
    public String getTelefoneEma() {
        return this.telefoneEma;
    }
    
    public void setTelefoneEma(String telefoneEma) {
        this.telefoneEma = telefoneEma;
    }

    
    @Column(name="email_ema")
    public String getEmailEma() {
        return this.emailEma;
    }
    
    public void setEmailEma(String emailEma) {
        this.emailEma = emailEma;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_cadastro_ema", length=10)
    public Date getDataCadastroEma() {
        return this.dataCadastroEma;
    }
    
    public void setDataCadastroEma(Date dataCadastroEma) {
        this.dataCadastroEma = dataCadastroEma;
    }

    
    @Column(name="pais_ema", length=10)
    public String getPaisEma() {
        return this.paisEma;
    }
    
    public void setPaisEma(String paisEma) {
        this.paisEma = paisEma;
    }

    
    @Column(name="estado_ema", length=100)
    public String getEstadoEma() {
        return this.estadoEma;
    }
    
    public void setEstadoEma(String estadoEma) {
        this.estadoEma = estadoEma;
    }

    
    @Column(name="estado_civil_ema", length=200)
    public String getEstadoCivilEma() {
        return this.estadoCivilEma;
    }
    
    public void setEstadoCivilEma(String estadoCivilEma) {
        this.estadoCivilEma = estadoCivilEma;
    }

    
    @Column(name="cpf_ema", length=14)
    public String getCpfEma() {
        return this.cpfEma;
    }
    
    public void setCpfEma(String cpfEma) {
        this.cpfEma = cpfEma;
    }

    
    @Column(name="rg_ema", length=100)
    public String getRgEma() {
        return this.rgEma;
    }
    
    public void setRgEma(String rgEma) {
        this.rgEma = rgEma;
    }

    
    @Column(name="profissao_ema", length=450)
    public String getProfissaoEma() {
        return this.profissaoEma;
    }
    
    public void setProfissaoEma(String profissaoEma) {
        this.profissaoEma = profissaoEma;
    }
    
    public String toString() {
        return nomeCompletoEma;
    }




}


