package bean;
// Generated 05/12/2023 10:44:54 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FuncionariosEma generated by hbm2java
 */
@Entity
@Table(name="funcionarios_ema"
    ,catalog="db_eduardo_aguero"
)
public class FuncionariosEma  implements java.io.Serializable {


     private int idFuncionarioEma;
     private String nomeCompletoEma;
     private Date dataNascimentoEma;
     private String generoEma;
     private String enderecoEma;
     private String cidadeEma;
     private String cepEma;
     private String telefoneEma;
     private String emailEma;
     private Date dataContratacaoEma;
     private String cargoEma;
     private String departamentoEma;
     private Double salarioEma;
     private String statusEma;

    public FuncionariosEma() {
    }

	
    public FuncionariosEma(int idFuncionarioEma) {
        this.idFuncionarioEma = idFuncionarioEma;
    }
    public FuncionariosEma(int idFuncionarioEma, String nomeCompletoEma, Date dataNascimentoEma, String generoEma, String enderecoEma, String cidadeEma, String cepEma, String telefoneEma, String emailEma, Date dataContratacaoEma, String cargoEma, String departamentoEma, Double salarioEma, String statusEma) {
       this.idFuncionarioEma = idFuncionarioEma;
       this.nomeCompletoEma = nomeCompletoEma;
       this.dataNascimentoEma = dataNascimentoEma;
       this.generoEma = generoEma;
       this.enderecoEma = enderecoEma;
       this.cidadeEma = cidadeEma;
       this.cepEma = cepEma;
       this.telefoneEma = telefoneEma;
       this.emailEma = emailEma;
       this.dataContratacaoEma = dataContratacaoEma;
       this.cargoEma = cargoEma;
       this.departamentoEma = departamentoEma;
       this.salarioEma = salarioEma;
       this.statusEma = statusEma;
    }
   
     @Id 

    
    @Column(name="id_funcionario_ema", unique=true, nullable=false)
    public int getIdFuncionarioEma() {
        return this.idFuncionarioEma;
    }
    
    public void setIdFuncionarioEma(int idFuncionarioEma) {
        this.idFuncionarioEma = idFuncionarioEma;
    }

    
    @Column(name="nome_completo_ema", length=100)
    public String getNomeCompletoEma() {
        return this.nomeCompletoEma;
    }
    
    public void setNomeCompletoEma(String nomeCompletoEma) {
        this.nomeCompletoEma = nomeCompletoEma;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_nascimento_ema", length=10)
    public Date getDataNascimentoEma() {
        return this.dataNascimentoEma;
    }
    
    public void setDataNascimentoEma(Date dataNascimentoEma) {
        this.dataNascimentoEma = dataNascimentoEma;
    }

    
    @Column(name="genero_ema", length=20)
    public String getGeneroEma() {
        return this.generoEma;
    }
    
    public void setGeneroEma(String generoEma) {
        this.generoEma = generoEma;
    }

    
    @Column(name="endereco_ema")
    public String getEnderecoEma() {
        return this.enderecoEma;
    }
    
    public void setEnderecoEma(String enderecoEma) {
        this.enderecoEma = enderecoEma;
    }

    
    @Column(name="cidade_ema", length=100)
    public String getCidadeEma() {
        return this.cidadeEma;
    }
    
    public void setCidadeEma(String cidadeEma) {
        this.cidadeEma = cidadeEma;
    }

    
    @Column(name="cep_ema", length=10)
    public String getCepEma() {
        return this.cepEma;
    }
    
    public void setCepEma(String cepEma) {
        this.cepEma = cepEma;
    }

    
    @Column(name="telefone_ema", length=20)
    public String getTelefoneEma() {
        return this.telefoneEma;
    }
    
    public void setTelefoneEma(String telefoneEma) {
        this.telefoneEma = telefoneEma;
    }

    
    @Column(name="email_ema")
    public String getEmailEma() {
        return this.emailEma;
    }
    
    public void setEmailEma(String emailEma) {
        this.emailEma = emailEma;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_contratacao_ema", length=10)
    public Date getDataContratacaoEma() {
        return this.dataContratacaoEma;
    }
    
    public void setDataContratacaoEma(Date dataContratacaoEma) {
        this.dataContratacaoEma = dataContratacaoEma;
    }

    
    @Column(name="cargo_ema", length=50)
    public String getCargoEma() {
        return this.cargoEma;
    }
    
    public void setCargoEma(String cargoEma) {
        this.cargoEma = cargoEma;
    }

    
    @Column(name="departamento_ema", length=50)
    public String getDepartamentoEma() {
        return this.departamentoEma;
    }
    
    public void setDepartamentoEma(String departamentoEma) {
        this.departamentoEma = departamentoEma;
    }

    
    @Column(name="salario_ema", precision=10)
    public Double getSalarioEma() {
        return this.salarioEma;
    }
    
    public void setSalarioEma(Double salarioEma) {
        this.salarioEma = salarioEma;
    }

    
    @Column(name="status_ema", length=10)
    public String getStatusEma() {
        return this.statusEma;
    }
    
    public void setStatusEma(String statusEma) {
        this.statusEma = statusEma;
    }
    
    public String toString() {
        return nomeCompletoEma;
    }




}


