package bean;
// Generated 05/12/2023 10:44:54 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsuariosEma generated by hbm2java
 */
@Entity
@Table(name="usuarios_ema"
    ,catalog="db_eduardo_aguero"
)
public class UsuariosEma  implements java.io.Serializable {


     private int idUsuarioEma;
     private String nomeUsuarioEma;
     private String nomeCompletoEma;
     private String emailEma;
     private String senhaEma;
     private Date dataNascimentoEma;
     private Date dataRegistroEma;

    public UsuariosEma() {
    }

	
    public UsuariosEma(int idUsuarioEma) {
        this.idUsuarioEma = idUsuarioEma;
    }
    public UsuariosEma(int idUsuarioEma, String nomeUsuarioEma, String nomeCompletoEma, String emailEma, String senhaEma, Date dataNascimentoEma, Date dataRegistroEma) {
       this.idUsuarioEma = idUsuarioEma;
       this.nomeUsuarioEma = nomeUsuarioEma;
       this.nomeCompletoEma = nomeCompletoEma;
       this.emailEma = emailEma;
       this.senhaEma = senhaEma;
       this.dataNascimentoEma = dataNascimentoEma;
       this.dataRegistroEma = dataRegistroEma;
    }
   
     @Id 

    
    @Column(name="id_usuario_ema", unique=true, nullable=false)
    public int getIdUsuarioEma() {
        return this.idUsuarioEma;
    }
    
    public void setIdUsuarioEma(int idUsuarioEma) {
        this.idUsuarioEma = idUsuarioEma;
    }

    
    @Column(name="nome_usuario_ema", length=50)
    public String getNomeUsuarioEma() {
        return this.nomeUsuarioEma;
    }
    
    public void setNomeUsuarioEma(String nomeUsuarioEma) {
        this.nomeUsuarioEma = nomeUsuarioEma;
    }

    
    @Column(name="nome_completo_ema", length=100)
    public String getNomeCompletoEma() {
        return this.nomeCompletoEma;
    }
    
    public void setNomeCompletoEma(String nomeCompletoEma) {
        this.nomeCompletoEma = nomeCompletoEma;
    }

    
    @Column(name="email_ema")
    public String getEmailEma() {
        return this.emailEma;
    }
    
    public void setEmailEma(String emailEma) {
        this.emailEma = emailEma;
    }

    
    @Column(name="senha_ema")
    public String getSenhaEma() {
        return this.senhaEma;
    }
    
    public void setSenhaEma(String senhaEma) {
        this.senhaEma = senhaEma;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_nascimento_ema", length=10)
    public Date getDataNascimentoEma() {
        return this.dataNascimentoEma;
    }
    
    public void setDataNascimentoEma(Date dataNascimentoEma) {
        this.dataNascimentoEma = dataNascimentoEma;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_registro_ema", length=10)
    public Date getDataRegistroEma() {
        return this.dataRegistroEma;
    }
    
    public void setDataRegistroEma(Date dataRegistroEma) {
        this.dataRegistroEma = dataRegistroEma;
    }




}


