package bean;
// Generated 05/12/2023 10:44:54 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendasEma generated by hbm2java
 */
@Entity
@Table(name = "vendas_ema",
         catalog = "db_eduardo_aguero"
)
public class VendasEma implements java.io.Serializable {

    private int idVendaEma;
    private Date dataVendaEma;
    private int fkClienteEma;
    private int fkFuncionarioEma;
    private Double totalVendaEma;
    private String metodoPagamentoEma;
    private String statusEntregaEma;
    private Set vendasProdutoEmas = new HashSet(0);

    public VendasEma() {
    }

    public VendasEma(int idVendaEma) {
        this.idVendaEma = idVendaEma;
    }

    public VendasEma(int idVendaEma, Date dataVendaEma, int fkClienteEma, int fkFuncionarioEma, Double totalVendaEma, String metodoPagamentoEma, String statusEntregaEma, Set vendasProdutoEmas) {
        this.idVendaEma = idVendaEma;
        this.dataVendaEma = dataVendaEma;
        this.fkClienteEma = fkClienteEma;
        this.fkFuncionarioEma = fkFuncionarioEma;
        this.totalVendaEma = totalVendaEma;
        this.metodoPagamentoEma = metodoPagamentoEma;
        this.statusEntregaEma = statusEntregaEma;
        this.vendasProdutoEmas = vendasProdutoEmas;
    }

    @Id

    @Column(name = "id_venda_ema", unique = true, nullable = false)
    public int getIdVendaEma() {
        return this.idVendaEma;
    }

    public void setIdVendaEma(int idVendaEma) {
        this.idVendaEma = idVendaEma;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "data_venda_ema", length = 10)
    public Date getDataVendaEma() {
        return this.dataVendaEma;
    }

    public void setDataVendaEma(Date dataVendaEma) {
        this.dataVendaEma = dataVendaEma;
    }

    @Column(name = "fk_cliente_ema")
    public int getFkClienteEma() {
        return this.fkClienteEma;
    }

    public void setFkClienteEma(int fkClienteEma) {
        this.fkClienteEma = fkClienteEma;
    }

    @Column(name = "fk_funcionario_ema")
    public int getFkFuncionarioEma() {
        return this.fkFuncionarioEma;
    }

    public void setFkFuncionarioEma(int fkFuncionarioEma) {
        this.fkFuncionarioEma = fkFuncionarioEma;
    }

    @Column(name = "total_venda_ema", precision = 10)
    public Double getTotalVendaEma() {
        return this.totalVendaEma;
    }

    public void setTotalVendaEma(Double totalVendaEma) {
        this.totalVendaEma = totalVendaEma;
    }

    @Column(name = "metodo_pagamento_ema", length = 50)
    public String getMetodoPagamentoEma() {
        return this.metodoPagamentoEma;
    }

    public void setMetodoPagamentoEma(String metodoPagamentoEma) {
        this.metodoPagamentoEma = metodoPagamentoEma;
    }

    @Column(name = "status_entrega_ema", length = 50)
    public String getStatusEntregaEma() {
        return this.statusEntregaEma;
    }

    public void setStatusEntregaEma(String statusEntregaEma) {
        this.statusEntregaEma = statusEntregaEma;
    }

    @OneToMany(mappedBy = "produtosEma", cascade = CascadeType.ALL, orphanRemoval = true)
    public Set<VendasProdutoEma> getVendasProdutoEmas() {
    return this.vendasProdutoEmas;
    }

    public void setVendasProdutoEmas(Set<VendasProdutoEma> vendasProdutoEmas) {
        this.vendasProdutoEmas = vendasProdutoEmas;
    }
    
    

}
