package bean;
// Generated 05/12/2023 10:44:54 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VendasProdutoEma generated by hbm2java
 */
@Entity
@Table(name = "vendas_produto_ema",
         catalog = "db_eduardo_aguero"
)
public class VendasProdutoEma implements java.io.Serializable {

    private int idVendaProdutoEma;
    private ProdutosEma produtosEma;
    private VendasEma vendasEma;
    private int quantidadeVendidaEma;
    private Double precoUnitarioEma;

    public VendasProdutoEma() {
    }

    public VendasProdutoEma(int idVendaProdutoEma) {
        this.idVendaProdutoEma = idVendaProdutoEma;
    }

    public VendasProdutoEma(int idVendaProdutoEma, ProdutosEma produtosEma, VendasEma vendasEma, int quantidadeVendidaEma, Double precoUnitarioEma) {
        this.idVendaProdutoEma = idVendaProdutoEma;
        this.produtosEma = produtosEma;
        this.vendasEma = vendasEma;
        this.quantidadeVendidaEma = quantidadeVendidaEma;
        this.precoUnitarioEma = precoUnitarioEma;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)

    @Column(name = "id_venda_produto_ema", unique = true, nullable = false)
    public int getIdVendaProdutoEma() {
        return this.idVendaProdutoEma;
    }

    public void setIdVendaProdutoEma(int idVendaProdutoEma) {
        this.idVendaProdutoEma = idVendaProdutoEma;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "fk_produto_ema")
    public ProdutosEma getProdutosEma() {
        return this.produtosEma;
    }

    public void setProdutosEma(ProdutosEma produtosEma) {
        this.produtosEma = produtosEma;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name = "vendaEmas") 
    public VendasEma getVendasEma() {
        return this.vendasEma;
    }

    public void setVendasEma(VendasEma vendasEma) {
        this.vendasEma = vendasEma;
    }

    @Column(name = "quantidade_vendida_ema")
    public int getQuantidadeVendidaEma() {
        return this.quantidadeVendidaEma;
    }

    public void setQuantidadeVendidaEma(int quantidadeVendidaEma) {
        this.quantidadeVendidaEma = quantidadeVendidaEma;
    }

    @Column(name = "preco_unitario_ema", precision = 10)
    public Double getPrecoUnitarioEma() {
        return this.precoUnitarioEma;
    }

    public void setPrecoUnitarioEma(Double precoUnitarioEma) {
        this.precoUnitarioEma = precoUnitarioEma;
    }

}
